// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StyleModuleScssNamespace {
  export interface IStyleModuleScss {
    active: string;
    button: string;
    fadeIn: string;
    fadeOut: string;
    icon: string;
  }
}

declare const StyleModuleScssModule: StyleModuleScssNamespace.IStyleModuleScss;

export = StyleModuleScssModule;
