// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StyleModuleScssNamespace {
  export interface IStyleModuleScss {
    button: string;
  }
}

declare const StyleModuleScssModule: StyleModuleScssNamespace.IStyleModuleScss;

export = StyleModuleScssModule;
