// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace HomeModuleScssNamespace {
  export interface IHomeModuleScss {
    about: string;
    actions: string;
    hero: string;
    links: string;
    main: string;
    name: string;
    subtitle: string;
  }
}

declare const HomeModuleScssModule: HomeModuleScssNamespace.IHomeModuleScss;

export = HomeModuleScssModule;
