// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace PlaygroundModuleScssNamespace {
  export interface IPlaygroundModuleScss {
    container: string;
    main: string;
    mainText: string;
    songCard: string;
    subText: string;
    trackOverlay: string;
  }
}

declare const PlaygroundModuleScssModule: PlaygroundModuleScssNamespace.IPlaygroundModuleScss;

export = PlaygroundModuleScssModule;
