// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace ProjectsModuleScssNamespace {
  export interface IProjectsModuleScss {
    card: string;
    container: string;
    dropin: string;
    main: string;
    projects: string;
    radioContainer: string;
  }
}

declare const ProjectsModuleScssModule: ProjectsModuleScssNamespace.IProjectsModuleScss;

export = ProjectsModuleScssModule;
