// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace ProjectsModuleScssNamespace {
  export interface IProjectsModuleScss {
    grid: string;
    main: string;
  }
}

declare const ProjectsModuleScssModule: ProjectsModuleScssNamespace.IProjectsModuleScss;

export = ProjectsModuleScssModule;
