// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StyleModuleScssNamespace {
  export interface IStyleModuleScss {
    card: string;
    desc: string;
    item: string;
  }
}

declare const StyleModuleScssModule: StyleModuleScssNamespace.IStyleModuleScss;

export = StyleModuleScssModule;
