// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    artist: string;
    currently: string;
    hidden: string;
    listenNow: string;
    pop: string;
    popAlbumCover: string;
    popButton: string;
    popPanel: string;
    popTextContent: string;
    title: string;
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss;

export = StylesModuleScssModule;
