// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StyleModuleScssNamespace {
  export interface IStyleModuleScss {
    loading: string;
    ripple: string;
  }
}

declare const StyleModuleScssModule: StyleModuleScssNamespace.IStyleModuleScss;

export = StyleModuleScssModule;
