// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StyleModuleScssNamespace {
  export interface IStyleModuleScss {
    container: string;
    mainText: string;
    songCard: string;
    songLeft: string;
    songRight: string;
    songSection: string;
    subText: string;
    trackOverlay: string;
  }
}

declare const StyleModuleScssModule: StyleModuleScssNamespace.IStyleModuleScss;

export = StyleModuleScssModule;
