import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { FaInstagram, FaFacebookF, FaLinkedinIn, FaGithub, FaSpotify } from "react-icons/fa";
import { SiDevpost } from "react-icons/si";
import { NextSeo } from "next-seo";

const links = [
  { link: "https://www.instagram.com/farisashai/", icon: <FaInstagram /> },
  { link: "https://www.facebook.com/farisashai/", icon: <FaFacebookF /> },
  { link: "https://www.linkedin.com/in/farisashai/", icon: <FaLinkedinIn /> },
  { link: "https://devpost.com/farisashai", icon: <SiDevpost /> },
  { link: "https://github.com/farisashai/", icon: <FaGithub /> },
  { link: "https://www.facebook.com", icon: <FaSpotify width={200} /> },
];

const Home: NextPage = () => {
  return (
    <>
      <NextSeo
        title="Home"
        titleTemplate="Faris Ashai | %s"
        defaultTitle="Faris Ashai"
        description="My portfolio. Current Software Engineering Intern at Apple and Vice President of Development at ACM UCSD"
        canonical="https://www.farisashai.me/"
        openGraph={{
          url: "https://www.farisashai.me/",
          title: "Faris Ashai | Home",
          description:
            "My portfolio. Current Software Engineering Intern at Apple and Vice President of Development at ACM UCSD",
          site_name: "Faris Ashai",
        }}
      />
      <main className={styles.main}>
        <h1 className={styles.name}>Faris Ashai</h1>
        <h3 className={styles.subtitle}>
          Hey, it&apos;s nice to see you! This website is still a work in progress. In the meantime,
          feel free to reach out to me or stay in touch below.
        </h3>
        <div className={styles.links}>
          {links.map(({ link, icon }, index) => (
            <a
              key={`${link}-${index}`}
              href={link}
              target="_blank"
              rel="noopener, noreferrer"
              aria-label="Link to social media platform"
            >
              {icon}
            </a>
          ))}
        </div>
      </main>
    </>
  );
};

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{" "}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   );
// };

export default Home;
